---
swagger: '2.0'
info:
  version: 0.0.1
  title: Product Catalog API
paths:
  /:
    get:
      summary: Product Categories
      description: |
        Returns different Product Categories available
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/ProductCategory'
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: "200"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:698225460402:function:prodcatalog/invocations"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws_proxy"

definitions:
  ProductCategory:
    type: object
    properties:
      product_id:
        type: integer
        description: Identifies a Product
      product_name:
        type: string
        description: A friendly name for the Product

